DROP TABLE IF EXISTS refundtbl;
DROP TABLE IF EXISTS canceltbl;
DROP TABLE IF EXISTS carttbl;
DROP TABLE IF EXISTS wishtbl;
DROP TABLE IF EXISTS purchasetbl;
DROP TABLE IF EXISTS Reviewtbl;
DROP TABLE IF EXISTS boardtbl;
DROP TABLE IF EXISTS Booktbl;
DROP TABLE IF EXISTS membertbl;

DROP DATABASE IF EXISTS MillkyWayDB;